### ISSUE TITLE
Exception when TV is switched into standby mode

### ISSUE THREAD

**Issue by thecode** [bendavid/aiopylgtv#47]
This exception happens when the TV is turned off, might be related that I have disabled the `Quick Start+` feature, 
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiopylgtv/webos_client.py", line 340, in ping_handler
    ping_waiter = await ws.ping()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 657, in ping
    await self.ensure_open()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 735, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1001 (going away), reason = server shutting down
```
The exception needs to be caught here: https://github.com/bendavid/aiopylgtv/blob/6b676ea69cb77f4e363d8fc5934cc126d07ad537/aiopylgtv/webos_client.py#L356-L359
I can make a PR to fix it if there is a plan to make a new release.

**Comment by chros73** [comment]
This one is [also done](https://github.com/chros73/bscpylgtv/commit/10e4d80a0e46332c49d48e7e26a8906b59e89a7a), thanks.
