### ISSUE TITLE
500 Application error, picture doesn't support the key(s)

### ISSUE THREAD

**Issue by SurPaul** [bendavid/aiopylgtv#49]
LG UJ620V. Any command ends in error even after successful pairing. It is worth mentioning that I am running `aiopylgtvcommand` from WSL with Debian. If the TV were completely turned off, a `TimeoutError` appears, so it's not a connection issue.

```
$ aiopylgtvcommand 192.168.1.41 volume_down
Traceback (most recent call last):
  File "/home/surpaul/.local/bin/aiopylgtvcommand", line 10, in <module>
    sys.exit(aiopylgtvcommand())
  File "/home/surpaul/.local/lib/python3.7/site-packages/aiopylgtv/utils.py", line 49, in aiopylgtvcommand
    asyncio.run(runloop(args))
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/surpaul/.local/lib/python3.7/site-packages/aiopylgtv/utils.py", line 9, in runloop
    await client.connect()
  File "/home/surpaul/.local/lib/python3.7/site-packages/aiopylgtv/webos_client.py", line 163, in connect
    return await self.connect_result
  File "/home/surpaul/.local/lib/python3.7/site-packages/aiopylgtv/webos_client.py", line 283, in connect_handler
    task.result()
  File "/home/surpaul/.local/lib/python3.7/site-packages/aiopylgtv/webos_client.py", line 1641, in subscribe_picture_settings
    return await self.subscribe(settings, ep.GET_SYSTEM_SETTINGS, payload=payload)
  File "/home/surpaul/.local/lib/python3.7/site-packages/aiopylgtv/webos_client.py", line 726, in subscribe
    uri, payload=payload, cmd_type="subscribe", uid=uid
  File "/home/surpaul/.local/lib/python3.7/site-packages/aiopylgtv/webos_client.py", line 711, in request
    raise PyLGTVCmdError(response)
aiopylgtv.webos_client.PyLGTVCmdError: {'type': 'error', 'id': 6, 'error': '500 Application error', 'payload': {'returnValue': False, 'errorCode': -1000, 'errorText': "category, picture doesn't support the key(s): contrast,backlight,brightness,color"}}
```

**Comment by chros73** [comment]
Same issue as #40
Try [bscpylgtv](https://github.com/chros73/bscpylgtv), it should work.

**Comment by SurPaul** [comment]
There really is no such error. Thanks!
